// Generated by `pnpm seed:generate`. Do not edit by hand.
import type { Mission } from "@/types";

export const publicMissions = [
  {
    "id": "p1-01-la-once",
    "slug": "la-once-de-tomatin",
    "course": "programming-1",
    "module": "Variables y operaciones",
    "order": 1,
    "title": "La once de Tomatin",
    "summary": "Calcula un total sin mezclar texto y números.",
    "context": "Hay que cerrar la compra del taller antes de que llegue el pedido.",
    "brief": "Implementa totalOnce. Recibe precios y cantidades en posiciones equivalentes y retorna la suma de precio por cantidad.",
    "difficulty": "Inicial",
    "points": 100,
    "duration": 12,
    "tags": [
      "variables",
      "arreglos",
      "acumuladores"
    ],
    "objectives": [
      "Recorrer dos colecciones relacionadas.",
      "Mantener un acumulador numérico.",
      "Resolver correctamente el caso vacío."
    ],
    "hints": [
      "El elemento en la posición i de precios corresponde a la posición i de cantidades.",
      "Parte el acumulador en cero y actualízalo una vez por producto."
    ],
    "variants": {
      "javascript": {
        "language": "javascript",
        "starterCode": "function totalOnce(precios, cantidades) {\n  // Retorna el total numérico.\n}\n",
        "publicTests": [
          {
            "id": "once-total",
            "label": "Suma dos productos",
            "expression": "totalOnce([1200, 850], [2, 3]) === 4950",
            "expected": "4950",
            "feedback": "Multiplica cada precio por su cantidad antes de sumar.",
            "actualExpression": "totalOnce([1200, 850], [2, 3])"
          },
          {
            "id": "once-empty",
            "label": "Acepta una compra vacía",
            "expression": "totalOnce([], []) === 0",
            "expected": "0",
            "feedback": "El acumulador debe comenzar en cero.",
            "actualExpression": "totalOnce([], [])"
          }
        ],
        "hiddenTestCount": 1
      },
      "python": {
        "language": "python",
        "starterCode": "def total_once(precios, cantidades):\n    # Retorna el total numérico.\n    pass\n",
        "publicTests": [
          {
            "id": "once-total",
            "label": "Suma dos productos",
            "expression": "total_once([1200, 850], [2, 3]) == 4950",
            "expected": "4950",
            "feedback": "Multiplica cada precio por su cantidad antes de sumar.",
            "actualExpression": "total_once([1200, 850], [2, 3])"
          },
          {
            "id": "once-empty",
            "label": "Acepta una compra vacía",
            "expression": "total_once([], []) == 0",
            "expected": "0",
            "feedback": "La suma de una colección vacía debe ser cero.",
            "actualExpression": "total_once([], [])"
          }
        ],
        "hiddenTestCount": 1
      },
      "cpp": {
        "language": "cpp",
        "starterCode": "#include <algorithm>\n#include <cmath>\n#include <deque>\n#include <iostream>\n#include <memory>\n#include <numeric>\n#include <optional>\n#include <queue>\n#include <regex>\n#include <string>\n#include <unordered_map>\n#include <unordered_set>\n#include <utility>\n#include <vector>\nusing namespace std;\n\ndouble totalOnce(const vector<double>& precios, const vector<int>& cantidades) {\n  // Retorna el total numérico.\n  return 0;\n}\n",
        "publicTests": [
          {
            "id": "once-total",
            "label": "Suma dos productos",
            "expression": "abs(totalOnce({1200, 850}, {2, 3}) - 4950) < 0.001",
            "expected": "4950",
            "feedback": "Multiplica cada precio por su cantidad antes de sumar."
          },
          {
            "id": "once-empty",
            "label": "Acepta una compra vacía",
            "expression": "abs(totalOnce({}, {})) < 0.001",
            "expected": "0",
            "feedback": "Inicializa el acumulador en cero."
          }
        ],
        "hiddenTestCount": 1
      }
    },
    "courseLabel": "Programación I",
    "version": 1
  },
  {
    "id": "p1-02-var-limache",
    "slug": "var-de-limache",
    "course": "programming-1",
    "module": "Condicionales",
    "order": 2,
    "title": "El VAR de Limache",
    "summary": "Combina condiciones booleanas sin casos ambiguos.",
    "context": "El marcador necesita una decisión consistente para cada jugada.",
    "brief": "Implementa revisarGol. Debe retornar GOL solo cuando no exista fuera de juego ni falta; en cualquier otro caso retorna ANULADO.",
    "difficulty": "Inicial",
    "points": 100,
    "duration": 10,
    "tags": [
      "booleanos",
      "condicionales"
    ],
    "objectives": [
      "Combinar dos condiciones booleanas.",
      "Expresar una regla con una salida clara."
    ],
    "hints": [
      "Para validar el gol, ambas infracciones deben ser falsas.",
      "Puedes resolverlo con una sola condición compuesta."
    ],
    "variants": {
      "javascript": {
        "language": "javascript",
        "starterCode": "function revisarGol(fueraDeJuego, falta) {\n  // Retorna \"GOL\" o \"ANULADO\".\n}\n",
        "publicTests": [
          {
            "id": "gol-valid",
            "label": "Gol válido",
            "expression": "revisarGol(false, false) === \"GOL\"",
            "expected": "GOL",
            "feedback": "Ambas infracciones deben ser falsas.",
            "actualExpression": "revisarGol(false, false)"
          },
          {
            "id": "gol-offside",
            "label": "Detecta fuera de juego",
            "expression": "revisarGol(true, false) === \"ANULADO\"",
            "expected": "ANULADO",
            "feedback": "El fuera de juego anula la jugada.",
            "actualExpression": "revisarGol(true, false)"
          }
        ],
        "hiddenTestCount": 2
      },
      "python": {
        "language": "python",
        "starterCode": "def revisar_gol(fuera_de_juego, falta):\n    # Retorna \"GOL\" o \"ANULADO\".\n    pass\n",
        "publicTests": [
          {
            "id": "gol-valid",
            "label": "Gol válido",
            "expression": "revisar_gol(False, False) == \"GOL\"",
            "expected": "GOL",
            "feedback": "Ambas infracciones deben ser falsas.",
            "actualExpression": "revisar_gol(False, False)"
          },
          {
            "id": "gol-offside",
            "label": "Detecta fuera de juego",
            "expression": "revisar_gol(True, False) == \"ANULADO\"",
            "expected": "ANULADO",
            "feedback": "El fuera de juego anula la jugada.",
            "actualExpression": "revisar_gol(True, False)"
          }
        ],
        "hiddenTestCount": 2
      },
      "cpp": {
        "language": "cpp",
        "starterCode": "#include <algorithm>\n#include <cmath>\n#include <deque>\n#include <iostream>\n#include <memory>\n#include <numeric>\n#include <optional>\n#include <queue>\n#include <regex>\n#include <string>\n#include <unordered_map>\n#include <unordered_set>\n#include <utility>\n#include <vector>\nusing namespace std;\n\nstring revisarGol(bool fueraDeJuego, bool falta) {\n  // Retorna \"GOL\" o \"ANULADO\".\n  return \"\";\n}\n",
        "publicTests": [
          {
            "id": "gol-valid",
            "label": "Gol válido",
            "expression": "revisarGol(false, false) == \"GOL\"",
            "expected": "GOL",
            "feedback": "Ambas infracciones deben ser falsas."
          },
          {
            "id": "gol-offside",
            "label": "Detecta fuera de juego",
            "expression": "revisarGol(true, false) == \"ANULADO\"",
            "expected": "ANULADO",
            "feedback": "El fuera de juego anula la jugada."
          }
        ],
        "hiddenTestCount": 2
      }
    },
    "courseLabel": "Programación I",
    "version": 1
  },
  {
    "id": "p1-03-semaforo-led",
    "slug": "semaforo-de-protoboard",
    "course": "programming-1",
    "module": "Bucles",
    "order": 3,
    "title": "Semáforo de protoboard",
    "summary": "Recorre una colección sin salir de sus límites.",
    "context": "Una secuencia de pines debe quedar lista para probar LEDs en el taller.",
    "brief": "Implementa secuenciaPines. Recibe números de pin y retorna un mensaje PIN n: ON por cada elemento, respetando el orden.",
    "difficulty": "Inicial",
    "points": 110,
    "duration": 14,
    "tags": [
      "bucles",
      "arreglos",
      "índices"
    ],
    "objectives": [
      "Recorrer todos los elementos de una colección.",
      "Evitar accesos fuera de rango.",
      "Construir una salida por cada pin."
    ],
    "hints": [
      "La condición del bucle debe detenerse antes del largo.",
      "Agrega una cadena al resultado en cada iteración."
    ],
    "variants": {
      "javascript": {
        "language": "javascript",
        "starterCode": "function secuenciaPines(pines) {\n  // Retorna un arreglo de mensajes.\n}\n",
        "publicTests": [
          {
            "id": "pins-three",
            "label": "Procesa tres pines",
            "expression": "JSON.stringify(secuenciaPines([2, 4, 7])) === JSON.stringify([\"PIN 2: ON\", \"PIN 4: ON\", \"PIN 7: ON\"])",
            "expected": "[\"PIN 2: ON\",\"PIN 4: ON\",\"PIN 7: ON\"]",
            "feedback": "Recorre exactamente los pines recibidos.",
            "actualExpression": "secuenciaPines([2, 4, 7])"
          },
          {
            "id": "pins-empty",
            "label": "Acepta una lista vacía",
            "expression": "secuenciaPines([]).length === 0",
            "expected": "[]",
            "feedback": "No agregues elementos si no hay pines.",
            "actualExpression": "secuenciaPines([])"
          }
        ],
        "hiddenTestCount": 1
      },
      "python": {
        "language": "python",
        "starterCode": "def secuencia_pines(pines):\n    # Retorna una lista de mensajes.\n    pass\n",
        "publicTests": [
          {
            "id": "pins-three",
            "label": "Procesa tres pines",
            "expression": "secuencia_pines([2, 4, 7]) == [\"PIN 2: ON\", \"PIN 4: ON\", \"PIN 7: ON\"]",
            "expected": "[\"PIN 2: ON\",\"PIN 4: ON\",\"PIN 7: ON\"]",
            "feedback": "Recorre exactamente los pines recibidos.",
            "actualExpression": "secuencia_pines([2, 4, 7])"
          },
          {
            "id": "pins-empty",
            "label": "Acepta una lista vacía",
            "expression": "secuencia_pines([]) == []",
            "expected": "[]",
            "feedback": "No agregues elementos si no hay pines.",
            "actualExpression": "secuencia_pines([])"
          }
        ],
        "hiddenTestCount": 1
      },
      "cpp": {
        "language": "cpp",
        "starterCode": "#include <algorithm>\n#include <cmath>\n#include <deque>\n#include <iostream>\n#include <memory>\n#include <numeric>\n#include <optional>\n#include <queue>\n#include <regex>\n#include <string>\n#include <unordered_map>\n#include <unordered_set>\n#include <utility>\n#include <vector>\nusing namespace std;\n\nvector<string> secuenciaPines(const vector<int>& pines) {\n  // Retorna un mensaje por cada pin.\n  return {};\n}\n",
        "publicTests": [
          {
            "id": "pins-three",
            "label": "Procesa tres pines",
            "expression": "secuenciaPines({2, 4, 7}) == vector<string>({\"PIN 2: ON\", \"PIN 4: ON\", \"PIN 7: ON\"})",
            "expected": "[\"PIN 2: ON\",\"PIN 4: ON\",\"PIN 7: ON\"]",
            "feedback": "Recorre exactamente los pines recibidos."
          },
          {
            "id": "pins-empty",
            "label": "Acepta una lista vacía",
            "expression": "secuenciaPines({}).empty()",
            "expected": "[]",
            "feedback": "No agregues elementos si no hay pines."
          }
        ],
        "hiddenTestCount": 1
      }
    },
    "courseLabel": "Programación I",
    "version": 1
  },
  {
    "id": "p1-04-conversor-hallulla",
    "slug": "conversor-de-hallullas",
    "course": "programming-1",
    "module": "Funciones y redondeo",
    "order": 4,
    "title": "Conversor de hallullas",
    "summary": "Convierte una cantidad y redondea hacia arriba.",
    "context": "La receta está en gramos y el inventario usa bolsas de medio kilo.",
    "brief": "Implementa bolsasNecesarias. Recibe gramos y retorna cuántas bolsas de 500 gramos se necesitan. Para cero o negativos retorna cero.",
    "difficulty": "Inicial",
    "points": 110,
    "duration": 12,
    "tags": [
      "funciones",
      "redondeo",
      "validación"
    ],
    "objectives": [
      "Aplicar división y redondeo superior.",
      "Definir un caso límite explícito."
    ],
    "hints": [
      "Divide los gramos por 500.",
      "La cantidad de bolsas no puede ser fraccionaria."
    ],
    "variants": {
      "javascript": {
        "language": "javascript",
        "starterCode": "function bolsasNecesarias(gramos) {\n  // Cada bolsa contiene 500 gramos.\n}\n",
        "publicTests": [
          {
            "id": "bags-exact",
            "label": "Cantidad exacta",
            "expression": "bolsasNecesarias(1000) === 2",
            "expected": "2",
            "feedback": "Una cantidad exacta no necesita una bolsa adicional.",
            "actualExpression": "bolsasNecesarias(1000)"
          },
          {
            "id": "bags-round",
            "label": "Redondea hacia arriba",
            "expression": "bolsasNecesarias(1001) === 3",
            "expected": "3",
            "feedback": "Usa redondeo superior.",
            "actualExpression": "bolsasNecesarias(1001)"
          }
        ],
        "hiddenTestCount": 1
      },
      "python": {
        "language": "python",
        "starterCode": "def bolsas_necesarias(gramos):\n    # Cada bolsa contiene 500 gramos.\n    pass\n",
        "publicTests": [
          {
            "id": "bags-exact",
            "label": "Cantidad exacta",
            "expression": "bolsas_necesarias(1000) == 2",
            "expected": "2",
            "feedback": "Una cantidad exacta no necesita una bolsa adicional.",
            "actualExpression": "bolsas_necesarias(1000)"
          },
          {
            "id": "bags-round",
            "label": "Redondea hacia arriba",
            "expression": "bolsas_necesarias(1001) == 3",
            "expected": "3",
            "feedback": "Usa redondeo superior.",
            "actualExpression": "bolsas_necesarias(1001)"
          }
        ],
        "hiddenTestCount": 1
      },
      "cpp": {
        "language": "cpp",
        "starterCode": "#include <algorithm>\n#include <cmath>\n#include <deque>\n#include <iostream>\n#include <memory>\n#include <numeric>\n#include <optional>\n#include <queue>\n#include <regex>\n#include <string>\n#include <unordered_map>\n#include <unordered_set>\n#include <utility>\n#include <vector>\nusing namespace std;\n\nint bolsasNecesarias(int gramos) {\n  // Cada bolsa contiene 500 gramos.\n  return 0;\n}\n",
        "publicTests": [
          {
            "id": "bags-exact",
            "label": "Cantidad exacta",
            "expression": "bolsasNecesarias(1000) == 2",
            "expected": "2",
            "feedback": "Una cantidad exacta no necesita una bolsa adicional."
          },
          {
            "id": "bags-round",
            "label": "Redondea hacia arriba",
            "expression": "bolsasNecesarias(1001) == 3",
            "expected": "3",
            "feedback": "Ajusta la división entera para redondear hacia arriba."
          }
        ],
        "hiddenTestCount": 1
      }
    },
    "courseLabel": "Programación I",
    "version": 1
  },
  {
    "id": "p1-05-esp-con-fiebre",
    "slug": "lecturas-del-esp",
    "course": "programming-1",
    "module": "Arreglos y promedio",
    "order": 5,
    "title": "Lecturas del ESP",
    "summary": "Detecta lecturas alejadas del promedio.",
    "context": "Un ESP registró temperaturas y necesitamos separar los valores anómalos.",
    "brief": "Implementa detectarAnomalias. Retorna las lecturas cuya distancia al promedio sea mayor que 8 grados. Para una lista vacía retorna una lista vacía.",
    "difficulty": "Intermedia",
    "points": 130,
    "duration": 18,
    "tags": [
      "arreglos",
      "promedio",
      "filtros"
    ],
    "objectives": [
      "Calcular un promedio.",
      "Filtrar datos con una regla numérica."
    ],
    "hints": [
      "Primero calcula el promedio de todas las lecturas.",
      "Usa el valor absoluto de la diferencia."
    ],
    "variants": {
      "javascript": {
        "language": "javascript",
        "starterCode": "function detectarAnomalias(lecturas) {\n  // Retorna solo las lecturas anómalas.\n}\n",
        "publicTests": [
          {
            "id": "temp-outlier",
            "label": "Detecta una lectura extrema",
            "expression": "JSON.stringify(detectarAnomalias([20, 21, 22, 45])) === JSON.stringify([45])",
            "expected": "[45]",
            "feedback": "Calcula el promedio antes de filtrar.",
            "actualExpression": "detectarAnomalias([20, 21, 22, 45])"
          },
          {
            "id": "temp-empty",
            "label": "Acepta una lista vacía",
            "expression": "detectarAnomalias([]).length === 0",
            "expected": "[]",
            "feedback": "Resuelve el caso vacío antes de dividir.",
            "actualExpression": "detectarAnomalias([])"
          }
        ],
        "hiddenTestCount": 1
      },
      "python": {
        "language": "python",
        "starterCode": "def detectar_anomalias(lecturas):\n    # Retorna solo las lecturas anómalas.\n    pass\n",
        "publicTests": [
          {
            "id": "temp-outlier",
            "label": "Detecta una lectura extrema",
            "expression": "detectar_anomalias([20, 21, 22, 45]) == [45]",
            "expected": "[45]",
            "feedback": "Calcula el promedio antes de filtrar.",
            "actualExpression": "detectar_anomalias([20, 21, 22, 45])"
          },
          {
            "id": "temp-empty",
            "label": "Acepta una lista vacía",
            "expression": "detectar_anomalias([]) == []",
            "expected": "[]",
            "feedback": "Resuelve el caso vacío antes de dividir.",
            "actualExpression": "detectar_anomalias([])"
          }
        ],
        "hiddenTestCount": 1
      },
      "cpp": {
        "language": "cpp",
        "starterCode": "#include <algorithm>\n#include <cmath>\n#include <deque>\n#include <iostream>\n#include <memory>\n#include <numeric>\n#include <optional>\n#include <queue>\n#include <regex>\n#include <string>\n#include <unordered_map>\n#include <unordered_set>\n#include <utility>\n#include <vector>\nusing namespace std;\n\nvector<double> detectarAnomalias(const vector<double>& lecturas) {\n  // Retorna solo las lecturas anómalas.\n  return {};\n}\n",
        "publicTests": [
          {
            "id": "temp-outlier",
            "label": "Detecta una lectura extrema",
            "expression": "detectarAnomalias({20, 21, 22, 45}) == vector<double>({45})",
            "expected": "[45]",
            "feedback": "Calcula el promedio antes de filtrar."
          },
          {
            "id": "temp-empty",
            "label": "Acepta una lista vacía",
            "expression": "detectarAnomalias({}).empty()",
            "expected": "[]",
            "feedback": "Resuelve el caso vacío antes de dividir."
          }
        ],
        "hiddenTestCount": 1
      }
    },
    "courseLabel": "Programación I",
    "version": 1
  },
  {
    "id": "p1-06-clave-del-profe",
    "slug": "clave-del-taller",
    "course": "programming-1",
    "module": "Cadenas",
    "order": 6,
    "title": "Clave del taller",
    "summary": "Normaliza y valida una cadena de entrada.",
    "context": "El acceso del laboratorio recibe claves escritas con espacios y mayúsculas variables.",
    "brief": "Implementa claveValida. Elimina espacios externos, convierte a minúsculas y valida el formato letras-guion-dos dígitos.",
    "difficulty": "Intermedia",
    "points": 130,
    "duration": 18,
    "tags": [
      "cadenas",
      "normalización",
      "expresiones regulares"
    ],
    "objectives": [
      "Normalizar una entrada.",
      "Validar una estructura completa."
    ],
    "hints": [
      "Normaliza antes de validar.",
      "La expresión debe cubrir la cadena completa y terminar con exactamente dos dígitos."
    ],
    "variants": {
      "javascript": {
        "language": "javascript",
        "starterCode": "function claveValida(entrada) {\n  // Retorna true si cumple letras-guion-dos dígitos.\n}\n",
        "publicTests": [
          {
            "id": "key-normalize",
            "label": "Normaliza espacios y mayúsculas",
            "expression": "claveValida(\"  ToMaTiN-42 \") === true",
            "expected": "true",
            "feedback": "Aplica trim y minúsculas antes de validar.",
            "actualExpression": "claveValida(\"  ToMaTiN-42 \")"
          },
          {
            "id": "key-shape",
            "label": "Rechaza un formato incompleto",
            "expression": "claveValida(\"tomatin-4\") === false",
            "expected": "false",
            "feedback": "Deben existir exactamente dos dígitos al final.",
            "actualExpression": "claveValida(\"tomatin-4\")"
          }
        ],
        "hiddenTestCount": 1
      },
      "python": {
        "language": "python",
        "starterCode": "def clave_valida(entrada):\n    # Retorna True si cumple letras-guion-dos dígitos.\n    pass\n",
        "publicTests": [
          {
            "id": "key-normalize",
            "label": "Normaliza espacios y mayúsculas",
            "expression": "clave_valida(\"  ToMaTiN-42 \") is True",
            "expected": "True",
            "feedback": "Aplica strip y minúsculas antes de validar.",
            "actualExpression": "clave_valida(\"  ToMaTiN-42 \")"
          },
          {
            "id": "key-shape",
            "label": "Rechaza un formato incompleto",
            "expression": "clave_valida(\"tomatin-4\") is False",
            "expected": "False",
            "feedback": "Deben existir exactamente dos dígitos al final.",
            "actualExpression": "clave_valida(\"tomatin-4\")"
          }
        ],
        "hiddenTestCount": 1
      },
      "cpp": {
        "language": "cpp",
        "starterCode": "#include <algorithm>\n#include <cmath>\n#include <deque>\n#include <iostream>\n#include <memory>\n#include <numeric>\n#include <optional>\n#include <queue>\n#include <regex>\n#include <string>\n#include <unordered_map>\n#include <unordered_set>\n#include <utility>\n#include <vector>\nusing namespace std;\n\nbool claveValida(string entrada) {\n  // Retorna true si cumple letras-guion-dos dígitos.\n  return false;\n}\n",
        "publicTests": [
          {
            "id": "key-normalize",
            "label": "Normaliza espacios y mayúsculas",
            "expression": "claveValida(\"  ToMaTiN-42 \")",
            "expected": "true",
            "feedback": "Recorta y transforma antes de validar."
          },
          {
            "id": "key-shape",
            "label": "Rechaza un formato incompleto",
            "expression": "!claveValida(\"tomatin-4\")",
            "expected": "false",
            "feedback": "Deben existir exactamente dos dígitos al final."
          }
        ],
        "hiddenTestCount": 1
      }
    },
    "courseLabel": "Programación I",
    "version": 1
  },
  {
    "id": "p1-07-inventario-maker",
    "slug": "inventario-maker",
    "course": "programming-1",
    "module": "Funciones y estado",
    "order": 7,
    "title": "Inventario maker",
    "summary": "Actualiza stock sin permitir cantidades inválidas.",
    "context": "El taller necesita registrar retiros sin terminar con stock negativo.",
    "brief": "Implementa stockSeguro y necesitaReposicion. stockSeguro retorna el nuevo stock o -1 si el retiro es negativo o supera lo disponible.",
    "difficulty": "Intermedia",
    "points": 140,
    "duration": 20,
    "tags": [
      "funciones",
      "validación",
      "estado"
    ],
    "objectives": [
      "Validar una transición de estado.",
      "Separar dos responsabilidades en funciones."
    ],
    "hints": [
      "Valida el retiro antes de restarlo.",
      "La reposición se necesita cuando el stock queda por debajo del mínimo."
    ],
    "variants": {
      "javascript": {
        "language": "javascript",
        "starterCode": "function stockSeguro(stock, retiro) {\n  // Retorna el nuevo stock o -1.\n}\n\nfunction necesitaReposicion(stock, minimo) {\n  // Retorna true o false.\n}\n",
        "publicTests": [
          {
            "id": "stock-update",
            "label": "Descuenta un retiro válido",
            "expression": "stockSeguro(12, 5) === 7",
            "expected": "7",
            "feedback": "Resta solo después de validar.",
            "actualExpression": "stockSeguro(12, 5)"
          },
          {
            "id": "stock-invalid",
            "label": "Impide stock negativo",
            "expression": "stockSeguro(4, 8) === -1",
            "expected": "-1",
            "feedback": "Un retiro mayor al stock debe rechazarse.",
            "actualExpression": "stockSeguro(4, 8)"
          }
        ],
        "hiddenTestCount": 1
      },
      "python": {
        "language": "python",
        "starterCode": "def stock_seguro(stock, retiro):\n    # Retorna el nuevo stock o -1.\n    pass\n\ndef necesita_reposicion(stock, minimo):\n    # Retorna True o False.\n    pass\n",
        "publicTests": [
          {
            "id": "stock-update",
            "label": "Descuenta un retiro válido",
            "expression": "stock_seguro(12, 5) == 7",
            "expected": "7",
            "feedback": "Resta solo después de validar.",
            "actualExpression": "stock_seguro(12, 5)"
          },
          {
            "id": "stock-invalid",
            "label": "Impide stock negativo",
            "expression": "stock_seguro(4, 8) == -1",
            "expected": "-1",
            "feedback": "Un retiro mayor al stock debe rechazarse.",
            "actualExpression": "stock_seguro(4, 8)"
          }
        ],
        "hiddenTestCount": 1
      },
      "cpp": {
        "language": "cpp",
        "starterCode": "#include <algorithm>\n#include <cmath>\n#include <deque>\n#include <iostream>\n#include <memory>\n#include <numeric>\n#include <optional>\n#include <queue>\n#include <regex>\n#include <string>\n#include <unordered_map>\n#include <unordered_set>\n#include <utility>\n#include <vector>\nusing namespace std;\n\nint stockSeguro(int stock, int retiro) {\n  // Retorna el nuevo stock o -1.\n  return -1;\n}\n\nbool necesitaReposicion(int stock, int minimo) {\n  // Retorna true o false.\n  return false;\n}\n",
        "publicTests": [
          {
            "id": "stock-update",
            "label": "Descuenta un retiro válido",
            "expression": "stockSeguro(12, 5) == 7",
            "expected": "7",
            "feedback": "Resta solo después de validar."
          },
          {
            "id": "stock-invalid",
            "label": "Impide stock negativo",
            "expression": "stockSeguro(4, 8) == -1",
            "expected": "-1",
            "feedback": "Un retiro mayor al stock debe rechazarse."
          }
        ],
        "hiddenTestCount": 1
      }
    },
    "courseLabel": "Programación I",
    "version": 1
  },
  {
    "id": "p1-08-loop-viernes",
    "slug": "bucle-con-limite",
    "course": "programming-1",
    "module": "Control de flujo",
    "order": 8,
    "title": "Bucle con límite",
    "summary": "Construye una iteración con una guarda explícita.",
    "context": "Un contador del taller debe detenerse incluso si recibe una entrada inesperada.",
    "brief": "Implementa contarHasta. Retorna los enteros desde 1 hasta límite. Para valores menores que 1 o mayores que 100 retorna una colección vacía.",
    "difficulty": "Intermedia",
    "points": 130,
    "duration": 16,
    "tags": [
      "bucles",
      "guardas",
      "límites"
    ],
    "objectives": [
      "Definir una condición de término.",
      "Proteger una iteración con límites de entrada."
    ],
    "hints": [
      "Valida el límite antes de iniciar el bucle.",
      "La última posición debe contener exactamente el límite."
    ],
    "variants": {
      "javascript": {
        "language": "javascript",
        "starterCode": "function contarHasta(limite) {\n  // Retorna [1, 2, ..., limite] o [].\n}\n",
        "publicTests": [
          {
            "id": "loop-five",
            "label": "Cuenta hasta cinco",
            "expression": "JSON.stringify(contarHasta(5)) === JSON.stringify([1, 2, 3, 4, 5])",
            "expected": "[1,2,3,4,5]",
            "feedback": "Revisa inicio, condición y avance.",
            "actualExpression": "contarHasta(5)"
          },
          {
            "id": "loop-cap",
            "label": "Aplica la guarda superior",
            "expression": "contarHasta(101).length === 0",
            "expected": "[]",
            "feedback": "Valida el máximo antes del bucle.",
            "actualExpression": "contarHasta(101)"
          }
        ],
        "hiddenTestCount": 1
      },
      "python": {
        "language": "python",
        "starterCode": "def contar_hasta(limite):\n    # Retorna [1, 2, ..., limite] o [].\n    pass\n",
        "publicTests": [
          {
            "id": "loop-five",
            "label": "Cuenta hasta cinco",
            "expression": "contar_hasta(5) == [1, 2, 3, 4, 5]",
            "expected": "[1,2,3,4,5]",
            "feedback": "Revisa inicio, condición y avance.",
            "actualExpression": "contar_hasta(5)"
          },
          {
            "id": "loop-cap",
            "label": "Aplica la guarda superior",
            "expression": "contar_hasta(101) == []",
            "expected": "[]",
            "feedback": "Valida el máximo antes del bucle.",
            "actualExpression": "contar_hasta(101)"
          }
        ],
        "hiddenTestCount": 1
      },
      "cpp": {
        "language": "cpp",
        "starterCode": "#include <algorithm>\n#include <cmath>\n#include <deque>\n#include <iostream>\n#include <memory>\n#include <numeric>\n#include <optional>\n#include <queue>\n#include <regex>\n#include <string>\n#include <unordered_map>\n#include <unordered_set>\n#include <utility>\n#include <vector>\nusing namespace std;\n\nvector<int> contarHasta(int limite) {\n  // Retorna {1, 2, ..., limite} o {}.\n  return {};\n}\n",
        "publicTests": [
          {
            "id": "loop-five",
            "label": "Cuenta hasta cinco",
            "expression": "contarHasta(5) == vector<int>({1, 2, 3, 4, 5})",
            "expected": "[1,2,3,4,5]",
            "feedback": "Revisa inicio, condición y avance."
          },
          {
            "id": "loop-cap",
            "label": "Aplica la guarda superior",
            "expression": "contarHasta(101).empty()",
            "expected": "[]",
            "feedback": "Valida el máximo antes del bucle."
          }
        ],
        "hiddenTestCount": 1
      }
    },
    "courseLabel": "Programación I",
    "version": 1
  },
  {
    "id": "p1-09-paltas-qa",
    "slug": "clasificador-de-paltas",
    "course": "programming-1",
    "module": "Casos límite",
    "order": 9,
    "title": "Clasificador de paltas",
    "summary": "Convierte una regla en una función comprobable.",
    "context": "El clasificador usa peso y madurez para separar piezas aptas.",
    "brief": "Implementa esApta. Retorna verdadero si el peso está entre 150 y 300 gramos y la madurez entre 3 y 5, incluyendo límites.",
    "difficulty": "Intermedia",
    "points": 140,
    "duration": 18,
    "tags": [
      "pruebas",
      "límites",
      "booleanos"
    ],
    "objectives": [
      "Traducir una especificación a condiciones.",
      "Cubrir límites válidos e inválidos."
    ],
    "hints": [
      "Comprueba ambos rangos.",
      "Los límites 150, 300, 3 y 5 son válidos."
    ],
    "variants": {
      "javascript": {
        "language": "javascript",
        "starterCode": "function esApta(peso, madurez) {\n  // Retorna true o false.\n}\n",
        "publicTests": [
          {
            "id": "avocado-center",
            "label": "Acepta un caso central",
            "expression": "esApta(220, 4) === true",
            "expected": "true",
            "feedback": "Ambos valores deben estar en rango.",
            "actualExpression": "esApta(220, 4)"
          },
          {
            "id": "avocado-weight",
            "label": "Rechaza peso inválido",
            "expression": "esApta(149, 4) === false",
            "expected": "false",
            "feedback": "Incluye el límite inferior correcto.",
            "actualExpression": "esApta(149, 4)"
          }
        ],
        "hiddenTestCount": 2
      },
      "python": {
        "language": "python",
        "starterCode": "def es_apta(peso, madurez):\n    # Retorna True o False.\n    pass\n",
        "publicTests": [
          {
            "id": "avocado-center",
            "label": "Acepta un caso central",
            "expression": "es_apta(220, 4) is True",
            "expected": "True",
            "feedback": "Ambos valores deben estar en rango.",
            "actualExpression": "es_apta(220, 4)"
          },
          {
            "id": "avocado-weight",
            "label": "Rechaza peso inválido",
            "expression": "es_apta(149, 4) is False",
            "expected": "False",
            "feedback": "Incluye el límite inferior correcto.",
            "actualExpression": "es_apta(149, 4)"
          }
        ],
        "hiddenTestCount": 2
      },
      "cpp": {
        "language": "cpp",
        "starterCode": "#include <algorithm>\n#include <cmath>\n#include <deque>\n#include <iostream>\n#include <memory>\n#include <numeric>\n#include <optional>\n#include <queue>\n#include <regex>\n#include <string>\n#include <unordered_map>\n#include <unordered_set>\n#include <utility>\n#include <vector>\nusing namespace std;\n\nbool esApta(int peso, int madurez) {\n  // Retorna true o false.\n  return false;\n}\n",
        "publicTests": [
          {
            "id": "avocado-center",
            "label": "Acepta un caso central",
            "expression": "esApta(220, 4)",
            "expected": "true",
            "feedback": "Ambos valores deben estar en rango."
          },
          {
            "id": "avocado-weight",
            "label": "Rechaza peso inválido",
            "expression": "!esApta(149, 4)",
            "expected": "false",
            "feedback": "Incluye el límite inferior correcto."
          }
        ],
        "hiddenTestCount": 2
      }
    },
    "courseLabel": "Programación I",
    "version": 1
  },
  {
    "id": "p1-10-marcador-naranja",
    "slug": "marcador-naranja",
    "course": "programming-1",
    "module": "Modelado simple",
    "order": 10,
    "title": "Marcador naranja",
    "summary": "Valida datos y construye un resumen estable.",
    "context": "El operador necesita un formato breve para goles, tarjetas y minuto.",
    "brief": "Implementa resumenMarcador. Retorna goles|tarjetas|minuto. Si un valor es negativo o el minuto supera 120, retorna ERROR.",
    "difficulty": "Intermedia",
    "points": 150,
    "duration": 20,
    "tags": [
      "validación",
      "cadenas",
      "funciones"
    ],
    "objectives": [
      "Validar varias entradas.",
      "Producir una salida con formato definido."
    ],
    "hints": [
      "Valida antes de construir la cadena.",
      "El minuto válido está entre 0 y 120, incluidos."
    ],
    "variants": {
      "javascript": {
        "language": "javascript",
        "starterCode": "function resumenMarcador(goles, tarjetas, minuto) {\n  // Retorna \"goles|tarjetas|minuto\" o \"ERROR\".\n}\n",
        "publicTests": [
          {
            "id": "score-format",
            "label": "Construye el resumen",
            "expression": "resumenMarcador(2, 3, 75) === \"2|3|75\"",
            "expected": "2|3|75",
            "feedback": "Respeta el orden y los separadores.",
            "actualExpression": "resumenMarcador(2, 3, 75)"
          },
          {
            "id": "score-minute",
            "label": "Rechaza minuto fuera de rango",
            "expression": "resumenMarcador(1, 0, 121) === \"ERROR\"",
            "expected": "ERROR",
            "feedback": "El minuto máximo es 120.",
            "actualExpression": "resumenMarcador(1, 0, 121)"
          }
        ],
        "hiddenTestCount": 1
      },
      "python": {
        "language": "python",
        "starterCode": "def resumen_marcador(goles, tarjetas, minuto):\n    # Retorna \"goles|tarjetas|minuto\" o \"ERROR\".\n    pass\n",
        "publicTests": [
          {
            "id": "score-format",
            "label": "Construye el resumen",
            "expression": "resumen_marcador(2, 3, 75) == \"2|3|75\"",
            "expected": "2|3|75",
            "feedback": "Respeta el orden y los separadores.",
            "actualExpression": "resumen_marcador(2, 3, 75)"
          },
          {
            "id": "score-minute",
            "label": "Rechaza minuto fuera de rango",
            "expression": "resumen_marcador(1, 0, 121) == \"ERROR\"",
            "expected": "ERROR",
            "feedback": "El minuto máximo es 120.",
            "actualExpression": "resumen_marcador(1, 0, 121)"
          }
        ],
        "hiddenTestCount": 1
      },
      "cpp": {
        "language": "cpp",
        "starterCode": "#include <algorithm>\n#include <cmath>\n#include <deque>\n#include <iostream>\n#include <memory>\n#include <numeric>\n#include <optional>\n#include <queue>\n#include <regex>\n#include <string>\n#include <unordered_map>\n#include <unordered_set>\n#include <utility>\n#include <vector>\nusing namespace std;\n\nstring resumenMarcador(int goles, int tarjetas, int minuto) {\n  // Retorna \"goles|tarjetas|minuto\" o \"ERROR\".\n  return \"\";\n}\n",
        "publicTests": [
          {
            "id": "score-format",
            "label": "Construye el resumen",
            "expression": "resumenMarcador(2, 3, 75) == \"2|3|75\"",
            "expected": "2|3|75",
            "feedback": "Respeta el orden y los separadores."
          },
          {
            "id": "score-minute",
            "label": "Rechaza minuto fuera de rango",
            "expression": "resumenMarcador(1, 0, 121) == \"ERROR\"",
            "expected": "ERROR",
            "feedback": "El minuto máximo es 120."
          }
        ],
        "hiddenTestCount": 1
      }
    },
    "courseLabel": "Programación I",
    "version": 1
  },
  {
    "id": "p2-01-factorial-recursivo",
    "slug": "factorial-recursivo",
    "course": "programming-2",
    "module": "Recursión",
    "order": 1,
    "title": "Factorial recursivo",
    "summary": "Define un caso base y reduce el problema.",
    "context": "La función debe terminar de forma predecible para cualquier entrada válida.",
    "brief": "Implementa factorial de forma recursiva. Para cero retorna 1 y para números negativos retorna -1.",
    "difficulty": "Intermedia",
    "points": 160,
    "duration": 18,
    "tags": [
      "recursión",
      "caso base"
    ],
    "objectives": [
      "Definir un caso base.",
      "Reducir una entrada recursivamente."
    ],
    "hints": [
      "Cero es un caso base.",
      "Cada llamada válida reduce n en uno."
    ],
    "variants": {
      "javascript": {
        "language": "javascript",
        "starterCode": "function factorial(n) {\n  // Usa recursión. Retorna -1 para negativos.\n}\n",
        "publicTests": [
          {
            "id": "fact-five",
            "label": "Calcula factorial de cinco",
            "expression": "factorial(5) === 120",
            "expected": "120",
            "feedback": "Multiplica n por el factorial del valor anterior.",
            "actualExpression": "factorial(5)"
          },
          {
            "id": "fact-zero",
            "label": "Resuelve el caso base",
            "expression": "factorial(0) === 1",
            "expected": "1",
            "feedback": "El factorial de cero es uno.",
            "actualExpression": "factorial(0)"
          }
        ],
        "hiddenTestCount": 2
      },
      "python": {
        "language": "python",
        "starterCode": "def factorial(n):\n    # Usa recursión. Retorna -1 para negativos.\n    pass\n",
        "publicTests": [
          {
            "id": "fact-five",
            "label": "Calcula factorial de cinco",
            "expression": "factorial(5) == 120",
            "expected": "120",
            "feedback": "Multiplica n por el factorial del valor anterior.",
            "actualExpression": "factorial(5)"
          },
          {
            "id": "fact-zero",
            "label": "Resuelve el caso base",
            "expression": "factorial(0) == 1",
            "expected": "1",
            "feedback": "El factorial de cero es uno.",
            "actualExpression": "factorial(0)"
          }
        ],
        "hiddenTestCount": 2
      },
      "cpp": {
        "language": "cpp",
        "starterCode": "#include <algorithm>\n#include <cmath>\n#include <deque>\n#include <iostream>\n#include <memory>\n#include <numeric>\n#include <optional>\n#include <queue>\n#include <regex>\n#include <string>\n#include <unordered_map>\n#include <unordered_set>\n#include <utility>\n#include <vector>\nusing namespace std;\n\nlong long factorial(int n) {\n  // Usa recursión. Retorna -1 para negativos.\n  return 0;\n}\n",
        "publicTests": [
          {
            "id": "fact-five",
            "label": "Calcula factorial de cinco",
            "expression": "factorial(5) == 120",
            "expected": "120",
            "feedback": "Multiplica n por el factorial del valor anterior."
          },
          {
            "id": "fact-zero",
            "label": "Resuelve el caso base",
            "expression": "factorial(0) == 1",
            "expected": "1",
            "feedback": "El factorial de cero es uno."
          }
        ],
        "hiddenTestCount": 2
      }
    },
    "courseLabel": "Programación II",
    "version": 1
  },
  {
    "id": "p2-02-duplicados-lineales",
    "slug": "duplicados-lineales",
    "course": "programming-2",
    "module": "Complejidad y conjuntos",
    "order": 2,
    "title": "Duplicados en una pasada",
    "summary": "Detecta valores repetidos en tiempo lineal esperado.",
    "context": "Una lista de credenciales puede crecer a miles de entradas.",
    "brief": "Implementa tieneDuplicados usando un conjunto. Retorna verdadero al encontrar la primera repetición.",
    "difficulty": "Intermedia",
    "points": 170,
    "duration": 18,
    "tags": [
      "complejidad",
      "sets",
      "hashing"
    ],
    "objectives": [
      "Usar una estructura de pertenencia.",
      "Evitar comparaciones cuadráticas."
    ],
    "hints": [
      "Guarda cada elemento que ya viste.",
      "Si un elemento ya está en el conjunto, puedes terminar."
    ],
    "variants": {
      "javascript": {
        "language": "javascript",
        "starterCode": "function tieneDuplicados(valores) {\n  // Usa un Set y evita bucles anidados.\n}\n",
        "publicTests": [
          {
            "id": "dupes-yes",
            "label": "Encuentra una repetición",
            "expression": "tieneDuplicados([4, 8, 2, 8]) === true",
            "expected": "true",
            "feedback": "Comprueba pertenencia antes de agregar.",
            "actualExpression": "tieneDuplicados([4, 8, 2, 8])"
          },
          {
            "id": "dupes-no",
            "label": "Acepta valores únicos",
            "expression": "tieneDuplicados([4, 8, 2, 1]) === false",
            "expected": "false",
            "feedback": "Retorna falso solo después de recorrer todo.",
            "actualExpression": "tieneDuplicados([4, 8, 2, 1])"
          }
        ],
        "hiddenTestCount": 1
      },
      "python": {
        "language": "python",
        "starterCode": "def tiene_duplicados(valores):\n    # Usa un set y evita bucles anidados.\n    pass\n",
        "publicTests": [
          {
            "id": "dupes-yes",
            "label": "Encuentra una repetición",
            "expression": "tiene_duplicados([4, 8, 2, 8]) is True",
            "expected": "True",
            "feedback": "Comprueba pertenencia antes de agregar.",
            "actualExpression": "tiene_duplicados([4, 8, 2, 8])"
          },
          {
            "id": "dupes-no",
            "label": "Acepta valores únicos",
            "expression": "tiene_duplicados([4, 8, 2, 1]) is False",
            "expected": "False",
            "feedback": "Retorna falso solo después de recorrer todo.",
            "actualExpression": "tiene_duplicados([4, 8, 2, 1])"
          }
        ],
        "hiddenTestCount": 1
      },
      "cpp": {
        "language": "cpp",
        "starterCode": "#include <algorithm>\n#include <cmath>\n#include <deque>\n#include <iostream>\n#include <memory>\n#include <numeric>\n#include <optional>\n#include <queue>\n#include <regex>\n#include <string>\n#include <unordered_map>\n#include <unordered_set>\n#include <utility>\n#include <vector>\nusing namespace std;\n\nbool tieneDuplicados(const vector<int>& valores) {\n  // Usa unordered_set y evita bucles anidados.\n  return false;\n}\n",
        "publicTests": [
          {
            "id": "dupes-yes",
            "label": "Encuentra una repetición",
            "expression": "tieneDuplicados({4, 8, 2, 8})",
            "expected": "true",
            "feedback": "Comprueba pertenencia antes de agregar."
          },
          {
            "id": "dupes-no",
            "label": "Acepta valores únicos",
            "expression": "!tieneDuplicados({4, 8, 2, 1})",
            "expected": "false",
            "feedback": "Retorna falso solo después de recorrer todo."
          }
        ],
        "hiddenTestCount": 1
      }
    },
    "courseLabel": "Programación II",
    "version": 1
  },
  {
    "id": "p2-03-busqueda-bodega",
    "slug": "busqueda-binaria",
    "course": "programming-2",
    "module": "Búsqueda",
    "order": 3,
    "title": "Búsqueda binaria",
    "summary": "Reduce a la mitad un espacio de búsqueda ordenado.",
    "context": "Los componentes están ordenados por código dentro del inventario.",
    "brief": "Implementa busquedaBinaria de forma iterativa. Retorna el índice del objetivo o -1 cuando no exista.",
    "difficulty": "Intermedia",
    "points": 180,
    "duration": 22,
    "tags": [
      "búsqueda binaria",
      "índices",
      "complejidad"
    ],
    "objectives": [
      "Mantener límites inclusivos.",
      "Descartar la mitad correcta en cada paso."
    ],
    "hints": [
      "Comienza con izquierda en cero y derecha en largo menos uno.",
      "Actualiza el límite sin volver a incluir el punto medio."
    ],
    "variants": {
      "javascript": {
        "language": "javascript",
        "starterCode": "function busquedaBinaria(valores, objetivo) {\n  // Retorna el índice o -1.\n}\n",
        "publicTests": [
          {
            "id": "binary-found",
            "label": "Encuentra un valor",
            "expression": "busquedaBinaria([2, 5, 8, 12, 20], 12) === 3",
            "expected": "3",
            "feedback": "Revisa cómo actualizas los límites.",
            "actualExpression": "busquedaBinaria([2, 5, 8, 12, 20], 12)"
          },
          {
            "id": "binary-missing",
            "label": "Retorna -1 si no existe",
            "expression": "busquedaBinaria([2, 5, 8, 12, 20], 7) === -1",
            "expected": "-1",
            "feedback": "El bucle termina cuando los límites se cruzan.",
            "actualExpression": "busquedaBinaria([2, 5, 8, 12, 20], 7)"
          }
        ],
        "hiddenTestCount": 1
      },
      "python": {
        "language": "python",
        "starterCode": "def busqueda_binaria(valores, objetivo):\n    # Retorna el índice o -1.\n    pass\n",
        "publicTests": [
          {
            "id": "binary-found",
            "label": "Encuentra un valor",
            "expression": "busqueda_binaria([2, 5, 8, 12, 20], 12) == 3",
            "expected": "3",
            "feedback": "Revisa cómo actualizas los límites.",
            "actualExpression": "busqueda_binaria([2, 5, 8, 12, 20], 12)"
          },
          {
            "id": "binary-missing",
            "label": "Retorna -1 si no existe",
            "expression": "busqueda_binaria([2, 5, 8, 12, 20], 7) == -1",
            "expected": "-1",
            "feedback": "El bucle termina cuando los límites se cruzan.",
            "actualExpression": "busqueda_binaria([2, 5, 8, 12, 20], 7)"
          }
        ],
        "hiddenTestCount": 1
      },
      "cpp": {
        "language": "cpp",
        "starterCode": "#include <algorithm>\n#include <cmath>\n#include <deque>\n#include <iostream>\n#include <memory>\n#include <numeric>\n#include <optional>\n#include <queue>\n#include <regex>\n#include <string>\n#include <unordered_map>\n#include <unordered_set>\n#include <utility>\n#include <vector>\nusing namespace std;\n\nint busquedaBinaria(const vector<int>& valores, int objetivo) {\n  // Retorna el índice o -1.\n  return -1;\n}\n",
        "publicTests": [
          {
            "id": "binary-found",
            "label": "Encuentra un valor",
            "expression": "busquedaBinaria({2, 5, 8, 12, 20}, 12) == 3",
            "expected": "3",
            "feedback": "Revisa cómo actualizas los límites."
          },
          {
            "id": "binary-missing",
            "label": "Retorna -1 si no existe",
            "expression": "busquedaBinaria({2, 5, 8, 12, 20}, 7) == -1",
            "expected": "-1",
            "feedback": "El bucle termina cuando los límites se cruzan."
          }
        ],
        "hiddenTestCount": 1
      }
    },
    "courseLabel": "Programación II",
    "version": 1
  },
  {
    "id": "p2-04-merge-sensores",
    "slug": "merge-sort-sensores",
    "course": "programming-2",
    "module": "Ordenamiento",
    "order": 4,
    "title": "Merge de sensores",
    "summary": "Ordena dividiendo y combinando colecciones.",
    "context": "Dos estaciones entregaron marcas de tiempo fuera de orden.",
    "brief": "Implementa mergeSort sin usar la función de ordenamiento incorporada. Retorna una colección nueva y no modifica la entrada.",
    "difficulty": "Avanzada",
    "points": 210,
    "duration": 30,
    "tags": [
      "merge sort",
      "recursión",
      "complejidad"
    ],
    "objectives": [
      "Dividir una colección.",
      "Combinar dos mitades ordenadas.",
      "Preservar la entrada."
    ],
    "hints": [
      "Una colección de largo cero o uno ya está ordenada.",
      "Combina comparando el primer elemento pendiente de cada mitad."
    ],
    "variants": {
      "javascript": {
        "language": "javascript",
        "starterCode": "function mergeSort(valores) {\n  // No uses Array.prototype.sort.\n}\n",
        "publicTests": [
          {
            "id": "merge-order",
            "label": "Ordena valores",
            "expression": "JSON.stringify(mergeSort([8, 3, 6, 1])) === JSON.stringify([1, 3, 6, 8])",
            "expected": "[1,3,6,8]",
            "feedback": "Comprueba la combinación de las dos mitades.",
            "actualExpression": "mergeSort([8, 3, 6, 1])"
          },
          {
            "id": "merge-copy",
            "label": "No modifica la entrada",
            "expression": "(() => { const x = [3, 1, 2]; mergeSort(x); return JSON.stringify(x) === JSON.stringify([3, 1, 2]); })()",
            "expected": "[3,1,2]",
            "feedback": "Trabaja con copias o segmentos nuevos."
          }
        ],
        "hiddenTestCount": 1
      },
      "python": {
        "language": "python",
        "starterCode": "def merge_sort(valores):\n    # No uses sorted ni list.sort.\n    pass\n",
        "publicTests": [
          {
            "id": "merge-order",
            "label": "Ordena valores",
            "expression": "merge_sort([8, 3, 6, 1]) == [1, 3, 6, 8]",
            "expected": "[1,3,6,8]",
            "feedback": "Comprueba la combinación de las dos mitades.",
            "actualExpression": "merge_sort([8, 3, 6, 1])"
          },
          {
            "id": "merge-copy",
            "label": "No modifica la entrada",
            "expression": "(lambda x: (merge_sort(x), x == [3, 1, 2])[-1])([3, 1, 2])",
            "expected": "[3,1,2]",
            "feedback": "Trabaja con copias o segmentos nuevos."
          }
        ],
        "hiddenTestCount": 1
      },
      "cpp": {
        "language": "cpp",
        "starterCode": "#include <algorithm>\n#include <cmath>\n#include <deque>\n#include <iostream>\n#include <memory>\n#include <numeric>\n#include <optional>\n#include <queue>\n#include <regex>\n#include <string>\n#include <unordered_map>\n#include <unordered_set>\n#include <utility>\n#include <vector>\nusing namespace std;\n\nvector<int> mergeSort(const vector<int>& valores) {\n  // No uses std::sort.\n  return {};\n}\n",
        "publicTests": [
          {
            "id": "merge-order",
            "label": "Ordena valores",
            "expression": "mergeSort({8, 3, 6, 1}) == vector<int>({1, 3, 6, 8})",
            "expected": "[1,3,6,8]",
            "feedback": "Comprueba la combinación de las dos mitades."
          },
          {
            "id": "merge-copy",
            "label": "No modifica la entrada",
            "expression": "[](){ vector<int> x{3,1,2}; mergeSort(x); return x == vector<int>({3,1,2}); }()",
            "expected": "[3,1,2]",
            "feedback": "Recibe la entrada como referencia constante."
          }
        ],
        "hiddenTestCount": 1
      }
    },
    "courseLabel": "Programación II",
    "version": 1
  },
  {
    "id": "p2-05-lista-jumpers",
    "slug": "lista-enlazada",
    "course": "programming-2",
    "module": "Estructuras enlazadas",
    "order": 5,
    "title": "Cadena de jumpers",
    "summary": "Mantén una lista enlazada y sus invariantes.",
    "context": "Cada elemento apunta al siguiente y el largo debe permanecer consistente.",
    "brief": "Implementa ListaEnlazada con agregar, eliminar y contiene. eliminar borra la primera coincidencia y retorna si encontró el valor.",
    "difficulty": "Avanzada",
    "points": 220,
    "duration": 34,
    "tags": [
      "listas enlazadas",
      "clases",
      "punteros"
    ],
    "objectives": [
      "Actualizar enlaces sin perder nodos.",
      "Mantener cabeza y largo consistentes."
    ],
    "hints": [
      "El caso de eliminar la cabeza es distinto.",
      "Guarda una referencia al nodo anterior mientras recorres."
    ],
    "variants": {
      "javascript": {
        "language": "javascript",
        "starterCode": "class ListaEnlazada {\n  constructor() {\n    this.cabeza = null;\n    this.largo = 0;\n  }\n\n  agregar(valor) {}\n  eliminar(valor) {}\n  contiene(valor) {}\n}\n",
        "publicTests": [
          {
            "id": "list-add",
            "label": "Agrega y encuentra",
            "expression": "(() => { const l = new ListaEnlazada(); l.agregar(3); l.agregar(5); return l.contiene(5) && l.largo === 2; })()",
            "expected": "true",
            "feedback": "Enlaza el nuevo nodo y actualiza el largo."
          },
          {
            "id": "list-remove-head",
            "label": "Elimina la cabeza",
            "expression": "(() => { const l = new ListaEnlazada(); l.agregar(3); l.agregar(5); return l.eliminar(3) && !l.contiene(3) && l.largo === 1; })()",
            "expected": "true",
            "feedback": "Actualiza cabeza cuando eliminas el primer nodo."
          }
        ],
        "hiddenTestCount": 1
      },
      "python": {
        "language": "python",
        "starterCode": "class ListaEnlazada:\n    def __init__(self):\n        self.cabeza = None\n        self.largo = 0\n\n    def agregar(self, valor):\n        pass\n\n    def eliminar(self, valor):\n        pass\n\n    def contiene(self, valor):\n        pass\n",
        "publicTests": [
          {
            "id": "list-add",
            "label": "Agrega y encuentra",
            "expression": "(lambda l: (l.agregar(3), l.agregar(5), l.contiene(5) and l.largo == 2)[-1])(ListaEnlazada())",
            "expected": "True",
            "feedback": "Enlaza el nuevo nodo y actualiza el largo."
          },
          {
            "id": "list-remove-head",
            "label": "Elimina la cabeza",
            "expression": "(lambda l: (l.agregar(3), l.agregar(5), l.eliminar(3) and not l.contiene(3) and l.largo == 1)[-1])(ListaEnlazada())",
            "expected": "True",
            "feedback": "Actualiza cabeza cuando eliminas el primer nodo."
          }
        ],
        "hiddenTestCount": 1
      },
      "cpp": {
        "language": "cpp",
        "starterCode": "#include <algorithm>\n#include <cmath>\n#include <deque>\n#include <iostream>\n#include <memory>\n#include <numeric>\n#include <optional>\n#include <queue>\n#include <regex>\n#include <string>\n#include <unordered_map>\n#include <unordered_set>\n#include <utility>\n#include <vector>\nusing namespace std;\n\nclass ListaEnlazada {\n  struct Nodo {\n    int valor;\n    Nodo* siguiente;\n  };\n  Nodo* cabeza = nullptr;\n  int largo_ = 0;\n\n public:\n  ~ListaEnlazada() {\n    // Libera los nodos.\n  }\n  void agregar(int valor) {}\n  bool eliminar(int valor) { return false; }\n  bool contiene(int valor) const { return false; }\n  int largo() const { return largo_; }\n};\n",
        "publicTests": [
          {
            "id": "list-add",
            "label": "Agrega y encuentra",
            "expression": "[](){ ListaEnlazada l; l.agregar(3); l.agregar(5); return l.contiene(5) && l.largo() == 2; }()",
            "expected": "true",
            "feedback": "Enlaza el nuevo nodo y actualiza el largo."
          },
          {
            "id": "list-remove-head",
            "label": "Elimina la cabeza",
            "expression": "[](){ ListaEnlazada l; l.agregar(3); l.agregar(5); return l.eliminar(3) && !l.contiene(3) && l.largo() == 1; }()",
            "expected": "true",
            "feedback": "Actualiza cabeza cuando eliminas el primer nodo."
          }
        ],
        "hiddenTestCount": 1
      }
    },
    "courseLabel": "Programación II",
    "version": 1
  },
  {
    "id": "p2-06-cola-taller",
    "slug": "cola-del-taller",
    "course": "programming-2",
    "module": "Colas",
    "order": 6,
    "title": "La fila del taller",
    "summary": "Implementa una cola con operaciones O(1).",
    "context": "Los equipos deben atenderse en el mismo orden en que llegan.",
    "brief": "Implementa Cola con encolar, desencolar, frente y estaVacia. No desplaces todos los elementos al desencolar.",
    "difficulty": "Avanzada",
    "points": 210,
    "duration": 28,
    "tags": [
      "colas",
      "FIFO",
      "complejidad"
    ],
    "objectives": [
      "Aplicar el orden FIFO.",
      "Mantener operaciones constantes."
    ],
    "hints": [
      "Mantén un índice o estructura dedicada para el frente.",
      "desencolar y frente deben manejar una cola vacía."
    ],
    "variants": {
      "javascript": {
        "language": "javascript",
        "starterCode": "class Cola {\n  constructor() {\n    this.datos = [];\n    this.inicio = 0;\n  }\n  encolar(valor) {}\n  desencolar() {}\n  frente() {}\n  estaVacia() {}\n}\n",
        "publicTests": [
          {
            "id": "queue-order",
            "label": "Respeta FIFO",
            "expression": "(() => { const q = new Cola(); q.encolar(4); q.encolar(8); return q.desencolar() === 4 && q.frente() === 8; })()",
            "expected": "true",
            "feedback": "El primer valor que entra debe ser el primero que sale."
          },
          {
            "id": "queue-empty",
            "label": "Maneja una cola vacía",
            "expression": "(() => { const q = new Cola(); return q.estaVacia() && q.desencolar() === null && q.frente() === null; })()",
            "expected": "true",
            "feedback": "Define una salida estable para la cola vacía."
          }
        ],
        "hiddenTestCount": 1
      },
      "python": {
        "language": "python",
        "starterCode": "class Cola:\n    def __init__(self):\n        self.datos = []\n        self.inicio = 0\n\n    def encolar(self, valor):\n        pass\n\n    def desencolar(self):\n        pass\n\n    def frente(self):\n        pass\n\n    def esta_vacia(self):\n        pass\n",
        "publicTests": [
          {
            "id": "queue-order",
            "label": "Respeta FIFO",
            "expression": "(lambda q: (q.encolar(4), q.encolar(8), q.desencolar() == 4 and q.frente() == 8)[-1])(Cola())",
            "expected": "True",
            "feedback": "El primer valor que entra debe ser el primero que sale."
          },
          {
            "id": "queue-empty",
            "label": "Maneja una cola vacía",
            "expression": "(lambda q: q.esta_vacia() and q.desencolar() is None and q.frente() is None)(Cola())",
            "expected": "True",
            "feedback": "Define una salida estable para la cola vacía."
          }
        ],
        "hiddenTestCount": 1
      },
      "cpp": {
        "language": "cpp",
        "starterCode": "#include <algorithm>\n#include <cmath>\n#include <deque>\n#include <iostream>\n#include <memory>\n#include <numeric>\n#include <optional>\n#include <queue>\n#include <regex>\n#include <string>\n#include <unordered_map>\n#include <unordered_set>\n#include <utility>\n#include <vector>\nusing namespace std;\n\nclass Cola {\n  deque<int> datos;\n\n public:\n  void encolar(int valor) {}\n  optional<int> desencolar() { return nullopt; }\n  optional<int> frente() const { return nullopt; }\n  bool estaVacia() const { return true; }\n};\n",
        "publicTests": [
          {
            "id": "queue-order",
            "label": "Respeta FIFO",
            "expression": "[](){ Cola q; q.encolar(4); q.encolar(8); return q.desencolar() == optional<int>(4) && q.frente() == optional<int>(8); }()",
            "expected": "true",
            "feedback": "El primer valor que entra debe ser el primero que sale."
          },
          {
            "id": "queue-empty",
            "label": "Maneja una cola vacía",
            "expression": "[](){ Cola q; return q.estaVacia() && !q.desencolar().has_value() && !q.frente().has_value(); }()",
            "expected": "true",
            "feedback": "Define una salida estable para la cola vacía."
          }
        ],
        "hiddenTestCount": 1
      }
    },
    "courseLabel": "Programación II",
    "version": 1
  },
  {
    "id": "p2-07-arbol-decisiones",
    "slug": "arbol-de-busqueda",
    "course": "programming-2",
    "module": "Árboles",
    "order": 7,
    "title": "Árbol de búsqueda",
    "summary": "Inserta y consulta valores manteniendo un orden.",
    "context": "El inventario necesita consultas que aprovechen su organización.",
    "brief": "Implementa ArbolBusqueda con insertar y contiene. Ignora duplicados y conserva la regla menor a la izquierda, mayor a la derecha.",
    "difficulty": "Avanzada",
    "points": 230,
    "duration": 34,
    "tags": [
      "árboles",
      "BST",
      "recursión"
    ],
    "objectives": [
      "Mantener la invariante de un BST.",
      "Recorrer solo la rama necesaria."
    ],
    "hints": [
      "Cada comparación elige una sola rama.",
      "Si el valor es igual, no insertes otro nodo."
    ],
    "variants": {
      "javascript": {
        "language": "javascript",
        "starterCode": "class ArbolBusqueda {\n  constructor() {\n    this.raiz = null;\n  }\n  insertar(valor) {}\n  contiene(valor) {}\n}\n",
        "publicTests": [
          {
            "id": "tree-find",
            "label": "Inserta y encuentra",
            "expression": "(() => { const a = new ArbolBusqueda(); [8, 3, 10, 6].forEach((x) => a.insertar(x)); return a.contiene(6) && !a.contiene(9); })()",
            "expected": "true",
            "feedback": "Compara y avanza por la rama correspondiente."
          },
          {
            "id": "tree-order",
            "label": "Mantiene el orden",
            "expression": "(() => { const a = new ArbolBusqueda(); [8, 3, 10].forEach((x) => a.insertar(x)); return a.raiz.izquierda.valor === 3 && a.raiz.derecha.valor === 10; })()",
            "expected": "true",
            "feedback": "Menores van a la izquierda y mayores a la derecha."
          }
        ],
        "hiddenTestCount": 1
      },
      "python": {
        "language": "python",
        "starterCode": "class ArbolBusqueda:\n    def __init__(self):\n        self.raiz = None\n\n    def insertar(self, valor):\n        pass\n\n    def contiene(self, valor):\n        pass\n",
        "publicTests": [
          {
            "id": "tree-find",
            "label": "Inserta y encuentra",
            "expression": "(lambda a: ([a.insertar(x) for x in [8, 3, 10, 6]], a.contiene(6) and not a.contiene(9))[-1])(ArbolBusqueda())",
            "expected": "True",
            "feedback": "Compara y avanza por la rama correspondiente."
          },
          {
            "id": "tree-order",
            "label": "Mantiene el orden",
            "expression": "(lambda a: ([a.insertar(x) for x in [8, 3, 10]], a.raiz['izquierda']['valor'] == 3 and a.raiz['derecha']['valor'] == 10)[-1])(ArbolBusqueda())",
            "expected": "True",
            "feedback": "Menores van a la izquierda y mayores a la derecha."
          }
        ],
        "hiddenTestCount": 1
      },
      "cpp": {
        "language": "cpp",
        "starterCode": "#include <algorithm>\n#include <cmath>\n#include <deque>\n#include <iostream>\n#include <memory>\n#include <numeric>\n#include <optional>\n#include <queue>\n#include <regex>\n#include <string>\n#include <unordered_map>\n#include <unordered_set>\n#include <utility>\n#include <vector>\nusing namespace std;\n\nclass ArbolBusqueda {\n  struct Nodo {\n    int valor;\n    unique_ptr<Nodo> izquierda;\n    unique_ptr<Nodo> derecha;\n  };\n  unique_ptr<Nodo> raiz;\n\n public:\n  bool insertar(int valor) { return false; }\n  bool contiene(int valor) const { return false; }\n};\n",
        "publicTests": [
          {
            "id": "tree-find",
            "label": "Inserta y encuentra",
            "expression": "[](){ ArbolBusqueda a; for (int x : {8,3,10,6}) a.insertar(x); return a.contiene(6) && !a.contiene(9); }()",
            "expected": "true",
            "feedback": "Compara y avanza por la rama correspondiente."
          },
          {
            "id": "tree-order",
            "label": "Encuentra ambos lados",
            "expression": "[](){ ArbolBusqueda a; for (int x : {8,3,10}) a.insertar(x); return a.contiene(3) && a.contiene(10); }()",
            "expected": "true",
            "feedback": "Menores van a la izquierda y mayores a la derecha."
          }
        ],
        "hiddenTestCount": 1
      }
    },
    "courseLabel": "Programación II",
    "version": 1
  },
  {
    "id": "p2-08-ruta-maker",
    "slug": "ruta-maker",
    "course": "programming-2",
    "module": "Grafos",
    "order": 8,
    "title": "Ruta maker",
    "summary": "Encuentra la menor cantidad de saltos con BFS.",
    "context": "Las sedes del circuito están conectadas como una red no ponderada.",
    "brief": "Implementa distanciaMinima sobre una lista de adyacencia. Retorna la cantidad de aristas de la ruta más corta o -1 si no existe.",
    "difficulty": "Avanzada",
    "points": 240,
    "duration": 38,
    "tags": [
      "grafos",
      "BFS",
      "colas"
    ],
    "objectives": [
      "Recorrer por niveles.",
      "Evitar visitar un nodo más de una vez."
    ],
    "hints": [
      "Guarda nodo y distancia en la cola.",
      "Marca cada nodo al encolarlo, no al retirarlo."
    ],
    "variants": {
      "javascript": {
        "language": "javascript",
        "starterCode": "function distanciaMinima(grafo, origen, destino) {\n  // grafo es un arreglo de listas de vecinos.\n}\n",
        "publicTests": [
          {
            "id": "graph-route",
            "label": "Encuentra la ruta mínima",
            "expression": "distanciaMinima([[1,2],[0,3],[0,3],[1,2,4],[3]], 0, 4) === 3",
            "expected": "3",
            "feedback": "BFS encuentra primero la menor distancia.",
            "actualExpression": "distanciaMinima([[1,2],[0,3],[0,3],[1,2,4],[3]], 0, 4)"
          },
          {
            "id": "graph-same",
            "label": "Resuelve origen igual a destino",
            "expression": "distanciaMinima([[1],[0]], 1, 1) === 0",
            "expected": "0",
            "feedback": "Comprueba el nodo retirado antes de expandirlo.",
            "actualExpression": "distanciaMinima([[1],[0]], 1, 1)"
          }
        ],
        "hiddenTestCount": 1
      },
      "python": {
        "language": "python",
        "starterCode": "def distancia_minima(grafo, origen, destino):\n    # grafo es una lista de listas de vecinos.\n    pass\n",
        "publicTests": [
          {
            "id": "graph-route",
            "label": "Encuentra la ruta mínima",
            "expression": "distancia_minima([[1,2],[0,3],[0,3],[1,2,4],[3]], 0, 4) == 3",
            "expected": "3",
            "feedback": "BFS encuentra primero la menor distancia.",
            "actualExpression": "distancia_minima([[1,2],[0,3],[0,3],[1,2,4],[3]], 0, 4)"
          },
          {
            "id": "graph-same",
            "label": "Resuelve origen igual a destino",
            "expression": "distancia_minima([[1],[0]], 1, 1) == 0",
            "expected": "0",
            "feedback": "Comprueba el nodo retirado antes de expandirlo.",
            "actualExpression": "distancia_minima([[1],[0]], 1, 1)"
          }
        ],
        "hiddenTestCount": 1
      },
      "cpp": {
        "language": "cpp",
        "starterCode": "#include <algorithm>\n#include <cmath>\n#include <deque>\n#include <iostream>\n#include <memory>\n#include <numeric>\n#include <optional>\n#include <queue>\n#include <regex>\n#include <string>\n#include <unordered_map>\n#include <unordered_set>\n#include <utility>\n#include <vector>\nusing namespace std;\n\nint distanciaMinima(const vector<vector<int>>& grafo, int origen, int destino) {\n  // Retorna la cantidad de aristas o -1.\n  return -1;\n}\n",
        "publicTests": [
          {
            "id": "graph-route",
            "label": "Encuentra la ruta mínima",
            "expression": "distanciaMinima({{1,2},{0,3},{0,3},{1,2,4},{3}}, 0, 4) == 3",
            "expected": "3",
            "feedback": "BFS encuentra primero la menor distancia."
          },
          {
            "id": "graph-same",
            "label": "Resuelve origen igual a destino",
            "expression": "distanciaMinima({{1},{0}}, 1, 1) == 0",
            "expected": "0",
            "feedback": "Comprueba el nodo retirado antes de expandirlo."
          }
        ],
        "hiddenTestCount": 1
      }
    },
    "courseLabel": "Programación II",
    "version": 1
  },
  {
    "id": "p2-09-frecuencias-serial",
    "slug": "frecuencias-del-serial",
    "course": "programming-2",
    "module": "Hashing",
    "order": 9,
    "title": "Frecuencias del serial",
    "summary": "Cuenta valores y conserva el primero en caso de empate.",
    "context": "El monitor serial repite estados y necesitamos identificar el más frecuente.",
    "brief": "Implementa masComun. Retorna el valor con mayor frecuencia; en empate conserva el que apareció primero. Para una lista vacía retorna una cadena vacía.",
    "difficulty": "Avanzada",
    "points": 210,
    "duration": 26,
    "tags": [
      "hashing",
      "frecuencias",
      "estabilidad"
    ],
    "objectives": [
      "Construir una tabla de frecuencias.",
      "Resolver empates de forma estable."
    ],
    "hints": [
      "Cuenta primero y luego recorre el orden original.",
      "Solo reemplaza el ganador si la frecuencia es estrictamente mayor."
    ],
    "variants": {
      "javascript": {
        "language": "javascript",
        "starterCode": "function masComun(valores) {\n  // Retorna el valor más frecuente.\n}\n",
        "publicTests": [
          {
            "id": "freq-most",
            "label": "Encuentra el más frecuente",
            "expression": "masComun([\"OK\", \"WARN\", \"OK\", \"ERROR\", \"OK\"]) === \"OK\"",
            "expected": "OK",
            "feedback": "Cuenta cada valor antes de elegir.",
            "actualExpression": "masComun([\"OK\", \"WARN\", \"OK\", \"ERROR\", \"OK\"])"
          },
          {
            "id": "freq-tie",
            "label": "Conserva el primero en empate",
            "expression": "masComun([\"WARN\", \"OK\", \"OK\", \"WARN\"]) === \"WARN\"",
            "expected": "WARN",
            "feedback": "No reemplaces al ganador cuando las frecuencias sean iguales.",
            "actualExpression": "masComun([\"WARN\", \"OK\", \"OK\", \"WARN\"])"
          }
        ],
        "hiddenTestCount": 1
      },
      "python": {
        "language": "python",
        "starterCode": "def mas_comun(valores):\n    # Retorna el valor más frecuente.\n    pass\n",
        "publicTests": [
          {
            "id": "freq-most",
            "label": "Encuentra el más frecuente",
            "expression": "mas_comun([\"OK\", \"WARN\", \"OK\", \"ERROR\", \"OK\"]) == \"OK\"",
            "expected": "OK",
            "feedback": "Cuenta cada valor antes de elegir.",
            "actualExpression": "mas_comun([\"OK\", \"WARN\", \"OK\", \"ERROR\", \"OK\"])"
          },
          {
            "id": "freq-tie",
            "label": "Conserva el primero en empate",
            "expression": "mas_comun([\"WARN\", \"OK\", \"OK\", \"WARN\"]) == \"WARN\"",
            "expected": "WARN",
            "feedback": "No reemplaces al ganador cuando las frecuencias sean iguales.",
            "actualExpression": "mas_comun([\"WARN\", \"OK\", \"OK\", \"WARN\"])"
          }
        ],
        "hiddenTestCount": 1
      },
      "cpp": {
        "language": "cpp",
        "starterCode": "#include <algorithm>\n#include <cmath>\n#include <deque>\n#include <iostream>\n#include <memory>\n#include <numeric>\n#include <optional>\n#include <queue>\n#include <regex>\n#include <string>\n#include <unordered_map>\n#include <unordered_set>\n#include <utility>\n#include <vector>\nusing namespace std;\n\nstring masComun(const vector<string>& valores) {\n  // Retorna el valor más frecuente.\n  return \"\";\n}\n",
        "publicTests": [
          {
            "id": "freq-most",
            "label": "Encuentra el más frecuente",
            "expression": "masComun({\"OK\", \"WARN\", \"OK\", \"ERROR\", \"OK\"}) == \"OK\"",
            "expected": "OK",
            "feedback": "Cuenta cada valor antes de elegir."
          },
          {
            "id": "freq-tie",
            "label": "Conserva el primero en empate",
            "expression": "masComun({\"WARN\", \"OK\", \"OK\", \"WARN\"}) == \"WARN\"",
            "expected": "WARN",
            "feedback": "No reemplaces al ganador cuando las frecuencias sean iguales."
          }
        ],
        "hiddenTestCount": 1
      }
    },
    "courseLabel": "Programación II",
    "version": 1
  },
  {
    "id": "p2-10-cambio-micro",
    "slug": "cambio-para-la-micro",
    "course": "programming-2",
    "module": "Programación dinámica",
    "order": 10,
    "title": "Cambio para la micro",
    "summary": "Encuentra la cantidad mínima de monedas.",
    "context": "Las denominaciones disponibles no siempre permiten una estrategia codiciosa.",
    "brief": "Implementa minMonedas con programación dinámica. Retorna la cantidad mínima o -1 cuando el monto no pueda formarse.",
    "difficulty": "Avanzada",
    "points": 260,
    "duration": 40,
    "tags": [
      "programación dinámica",
      "optimización"
    ],
    "objectives": [
      "Definir estados y transiciones.",
      "Distinguir estados inalcanzables."
    ],
    "hints": [
      "dp[x] puede representar la mejor respuesta para el monto x.",
      "Inicializa dp[0] en cero y los demás estados como inalcanzables."
    ],
    "variants": {
      "javascript": {
        "language": "javascript",
        "starterCode": "function minMonedas(monedas, monto) {\n  // Retorna la cantidad mínima o -1.\n}\n",
        "publicTests": [
          {
            "id": "coins-nongreedy",
            "label": "Supera el caso no codicioso",
            "expression": "minMonedas([1, 3, 4], 6) === 2",
            "expected": "2",
            "feedback": "Considera todas las denominaciones para cada monto.",
            "actualExpression": "minMonedas([1, 3, 4], 6)"
          },
          {
            "id": "coins-zero",
            "label": "Resuelve monto cero",
            "expression": "minMonedas([2, 5], 0) === 0",
            "expected": "0",
            "feedback": "El estado base necesita cero monedas.",
            "actualExpression": "minMonedas([2, 5], 0)"
          }
        ],
        "hiddenTestCount": 2
      },
      "python": {
        "language": "python",
        "starterCode": "def min_monedas(monedas, monto):\n    # Retorna la cantidad mínima o -1.\n    pass\n",
        "publicTests": [
          {
            "id": "coins-nongreedy",
            "label": "Supera el caso no codicioso",
            "expression": "min_monedas([1, 3, 4], 6) == 2",
            "expected": "2",
            "feedback": "Considera todas las denominaciones para cada monto.",
            "actualExpression": "min_monedas([1, 3, 4], 6)"
          },
          {
            "id": "coins-zero",
            "label": "Resuelve monto cero",
            "expression": "min_monedas([2, 5], 0) == 0",
            "expected": "0",
            "feedback": "El estado base necesita cero monedas.",
            "actualExpression": "min_monedas([2, 5], 0)"
          }
        ],
        "hiddenTestCount": 2
      },
      "cpp": {
        "language": "cpp",
        "starterCode": "#include <algorithm>\n#include <cmath>\n#include <deque>\n#include <iostream>\n#include <memory>\n#include <numeric>\n#include <optional>\n#include <queue>\n#include <regex>\n#include <string>\n#include <unordered_map>\n#include <unordered_set>\n#include <utility>\n#include <vector>\nusing namespace std;\n\nint minMonedas(const vector<int>& monedas, int monto) {\n  // Retorna la cantidad mínima o -1.\n  return -1;\n}\n",
        "publicTests": [
          {
            "id": "coins-nongreedy",
            "label": "Supera el caso no codicioso",
            "expression": "minMonedas({1, 3, 4}, 6) == 2",
            "expected": "2",
            "feedback": "Considera todas las denominaciones para cada monto."
          },
          {
            "id": "coins-zero",
            "label": "Resuelve monto cero",
            "expression": "minMonedas({2, 5}, 0) == 0",
            "expected": "0",
            "feedback": "El estado base necesita cero monedas."
          }
        ],
        "hiddenTestCount": 2
      }
    },
    "courseLabel": "Programación II",
    "version": 1
  }
] satisfies Mission[];
