import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { secureMissions as missions } from "../v2/src/data/missions-secure";
import { LANGUAGES } from "../v2/src/types";

function sql(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

function json(value: unknown): string {
  return `${sql(JSON.stringify(value))}::jsonb`;
}

const statements: string[] = [
  "-- Generated by `pnpm seed:generate`. Do not edit by hand.",
  "begin;",
];

const publicMissions = missions.map((mission) => ({
  ...mission,
  variants: Object.fromEntries(
    LANGUAGES.map((language) => {
      const variant = mission.variants[language];
      return [
        language,
        {
          language,
          starterCode: variant.starterCode,
          publicTests: variant.publicTests,
          hiddenTestCount: variant.hiddenTests?.length ?? 0,
        },
      ];
    }),
  ),
}));

for (const mission of missions) {
  const {
    variants: _variants,
    id,
    slug,
    course,
    title,
    version,
    ...content
  } = mission;

  statements.push(`
insert into public.missions (id, slug, course, title, current_version)
values (${sql(id)}, ${sql(slug)}, ${sql(course)}, ${sql(title)}, ${version})
on conflict (id) do update set
  slug = excluded.slug,
  course = excluded.course,
  title = excluded.title,
  current_version = excluded.current_version;

insert into public.mission_versions (
  mission_id,
  version,
  status,
  content,
  published_at
)
values (
  ${sql(id)},
  ${version},
  'published',
  ${json({ id, slug, course, title, version, ...content })},
  now()
)
on conflict (mission_id, version) do update set
  status = 'published',
  content = excluded.content,
  published_at = coalesce(public.mission_versions.published_at, now());`);

  for (const language of LANGUAGES) {
    const variant = mission.variants[language];
    statements.push(`
insert into public.mission_variants (
  mission_version_id,
  language,
  starter_code,
  public_tests,
  hidden_test_count
)
select
  version.id,
  ${sql(language)},
  ${sql(variant.starterCode)},
  ${json(variant.publicTests)},
  ${variant.hiddenTests?.length ?? 0}
from public.mission_versions version
where version.mission_id = ${sql(id)}
  and version.version = ${version}
on conflict (mission_version_id, language) do update set
  starter_code = excluded.starter_code,
  public_tests = excluded.public_tests,
  hidden_test_count = excluded.hidden_test_count;

insert into private.mission_variants_secure (
  variant_id,
  reference_solution,
  hidden_tests
)
select
  variant.id,
  ${sql(variant.referenceSolution!)},
  ${json(variant.hiddenTests!)}
from public.mission_variants variant
join public.mission_versions version on version.id = variant.mission_version_id
where version.mission_id = ${sql(id)}
  and version.version = ${version}
  and variant.language = ${sql(language)}
on conflict (variant_id) do update set
  reference_solution = excluded.reference_solution,
  hidden_tests = excluded.hidden_tests,
  updated_at = now();`);
  }
}

statements.push("commit;", "");

const destination = resolve("supabase/seed.sql");
const migrationDestination = resolve(
  "supabase/migrations/202607250002_mission_catalog.sql",
);
const publicDestination = resolve(
  "v2/src/data/missions-public.generated.ts",
);
await Promise.all([
  writeFile(destination, statements.join("\n"), "utf8"),
  writeFile(migrationDestination, statements.join("\n"), "utf8"),
  writeFile(
    publicDestination,
    `// Generated by \`pnpm seed:generate\`. Do not edit by hand.
import type { Mission } from "@/types";

export const publicMissions = ${JSON.stringify(publicMissions, null, 2)} satisfies Mission[];
`,
    "utf8",
  ),
]);
console.log(
  `Generated database seed and public catalog: ${missions.length} missions / ${missions.length * LANGUAGES.length} variants.`,
);
